-- ============================================================
-- 用户咨询问题标签系统：年龄/人生阶段 + 咨询问题分类
-- 与咨询师擅长领域(specialty_categories/tags)完全独立
-- ============================================================

USE mental_health_db;

-- 1. 年龄/人生阶段表（一级分类）
CREATE TABLE IF NOT EXISTS life_stages (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '阶段ID',
    code VARCHAR(50) UNIQUE NOT NULL COMMENT '阶段编码',
    name VARCHAR(50) NOT NULL COMMENT '阶段名称',
    icon VARCHAR(100) COMMENT '图标',
    sort_order INT DEFAULT 0 COMMENT '排序',
    is_enabled BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='年龄/人生阶段表';

-- 2. 咨询问题标签表（二级问题）
CREATE TABLE IF NOT EXISTS consultation_issues (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '问题ID',
    stage_id BIGINT NOT NULL COMMENT '所属阶段ID',
    category_name VARCHAR(100) NOT NULL COMMENT '问题分类名称，如: 饮食喂养类',
    issue_name VARCHAR(100) NOT NULL COMMENT '具体问题名称，如: 喂养抗拒',
    is_custom_input BOOLEAN DEFAULT FALSE COMMENT '是否为"其它"自定义输入项',
    sort_order INT DEFAULT 0 COMMENT '排序',
    is_enabled BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (stage_id) REFERENCES life_stages(id) ON DELETE CASCADE,
    INDEX idx_stage_id (stage_id),
    INDEX idx_category_name (category_name),
    INDEX idx_is_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='咨询问题标签表';

-- 3. 插入10个年龄/人生阶段
INSERT INTO life_stages (code, name, icon, sort_order) VALUES
('newborn', '0-1岁新生儿', '👶', 1),
('infant', '1-2岁婴幼儿', '🍼', 2),
('kindergarten', '3-6岁幼儿园', '🧸', 3),
('primary_school', '7-12岁小学', '📚', 4),
('middle_high_school', '13-18岁初高中', '🎓', 5),
('college', '19-22+岁大学生', '🏫', 6),
('society', '步入社会', '💼', 7),
('marriage', '婚前婚后', '💑', 8),
('property_division', '分家|财产分割', '⚖️', 9),
('elderly_care', '养老|赡养', '👴', 10);

-- 4. 插入各阶段下的咨询问题（基于PDF内容）

-- ========== 0-1岁新生儿 ==========
SET @stage_newborn = (SELECT id FROM life_stages WHERE code = 'newborn');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_newborn, '饮食喂养类', '喂养抗拒', 1),
(@stage_newborn, '饮食喂养类', '饮食习惯差', 2),
(@stage_newborn, '饮食喂养类', '饮食作息混乱', 3),
(@stage_newborn, '饮食喂养类', '进食能力薄弱', 4),
(@stage_newborn, '饮食喂养类', '喂养误区', 5),
(@stage_newborn, '睡眠作息类', '入睡困难', 6),
(@stage_newborn, '睡眠作息类', '睡眠不安稳', 7),
(@stage_newborn, '睡眠作息类', '作息颠倒', 8),
(@stage_newborn, '睡眠作息类', '不良睡眠习惯', 9),
(@stage_newborn, '睡眠作息类', '睡眠时间不足', 10),
(@stage_newborn, '行为习惯养成类', '自控力薄弱', 11),
(@stage_newborn, '行为习惯养成类', '秩序感缺失', 12),
(@stage_newborn, '行为习惯养成类', '过度黏人', 13),
(@stage_newborn, '行为习惯养成类', '任性执拗', 14),
(@stage_newborn, '行为习惯养成类', '自理起步缓慢', 15),
(@stage_newborn, '情绪性格心理类', '情绪敏感脆弱', 16),
(@stage_newborn, '情绪性格心理类', '情绪暴躁易怒', 17),
(@stage_newborn, '情绪性格心理类', '安全感缺失', 18),
(@stage_newborn, '情绪性格心理类', '性格内向孤僻', 19),
(@stage_newborn, '情绪性格心理类', '情绪表达单一', 20),
(@stage_newborn, '语言发育启蒙类', '开口迟缓', 21),
(@stage_newborn, '语言发育启蒙类', '语言反应迟钝', 22),
(@stage_newborn, '语言发育启蒙类', '表达意愿低', 23),
(@stage_newborn, '语言发育启蒙类', '家庭启蒙缺失', 24),
(@stage_newborn, '语言发育启蒙类', '口齿发育问题', 25),
(@stage_newborn, '大运动与精细动作类', '大运动发育滞后', 26),
(@stage_newborn, '大运动与精细动作类', '肢体协调性差', 27),
(@stage_newborn, '大运动与精细动作类', '精细动作薄弱', 28),
(@stage_newborn, '大运动与精细动作类', '运动兴趣低下', 29),
(@stage_newborn, '大运动与精细动作类', '家长过度保护', 30),
(@stage_newborn, '社交适应能力类', '认生严重', 31),
(@stage_newborn, '社交适应能力类', '不会同伴相处', 32),
(@stage_newborn, '社交适应能力类', '互动意愿差', 33),
(@stage_newborn, '社交适应能力类', '集体适应困难', 34),
(@stage_newborn, '社交适应能力类', '自我意识过强', 35),
(@stage_newborn, '亲子陪伴家庭教育类', '陪伴质量低', 36),
(@stage_newborn, '亲子陪伴家庭教育类', '教育方式极端', 37),
(@stage_newborn, '亲子陪伴家庭教育类', '育儿观念分歧', 38),
(@stage_newborn, '亲子陪伴家庭教育类', '过度包办代替', 39),
(@stage_newborn, '亲子陪伴家庭教育类', '情绪影响孩子', 40),
(@stage_newborn, '健康卫生习惯类', '卫生意识薄弱', 41),
(@stage_newborn, '健康卫生习惯类', '体质抵抗力差', 42),
(@stage_newborn, '健康卫生习惯类', '沉迷电子产品', 43),
(@stage_newborn, '健康卫生习惯类', '日常护理不当', 44),
(@stage_newborn, '健康卫生习惯类', '卫生习惯未培养', 45),
(@stage_newborn, '饮食喂养类', '其它', 999);

-- ========== 1-2岁婴幼儿 ==========
SET @stage_infant = (SELECT id FROM life_stages WHERE code = 'infant');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_infant, '饮食喂养类', '喂养抗拒', 1),
(@stage_infant, '饮食喂养类', '饮食习惯差', 2),
(@stage_infant, '饮食喂养类', '饮食作息混乱', 3),
(@stage_infant, '饮食喂养类', '进食能力薄弱', 4),
(@stage_infant, '饮食喂养类', '喂养误区', 5),
(@stage_infant, '睡眠作息类', '入睡困难', 6),
(@stage_infant, '睡眠作息类', '睡眠不安稳', 7),
(@stage_infant, '睡眠作息类', '作息颠倒', 8),
(@stage_infant, '睡眠作息类', '不良睡眠习惯', 9),
(@stage_infant, '睡眠作息类', '睡眠时间不足', 10),
(@stage_infant, '行为习惯养成类', '自控力薄弱', 11),
(@stage_infant, '行为习惯养成类', '秩序感缺失', 12),
(@stage_infant, '行为习惯养成类', '过度黏人', 13),
(@stage_infant, '行为习惯养成类', '任性执拗', 14),
(@stage_infant, '行为习惯养成类', '自理起步缓慢', 15),
(@stage_infant, '情绪性格心理类', '情绪敏感脆弱', 16),
(@stage_infant, '情绪性格心理类', '情绪暴躁易怒', 17),
(@stage_infant, '情绪性格心理类', '安全感缺失', 18),
(@stage_infant, '情绪性格心理类', '性格内向孤僻', 19),
(@stage_infant, '情绪性格心理类', '情绪表达单一', 20),
(@stage_infant, '语言发育启蒙类', '开口迟缓', 21),
(@stage_infant, '语言发育启蒙类', '语言反应迟钝', 22),
(@stage_infant, '语言发育启蒙类', '表达意愿低', 23),
(@stage_infant, '语言发育启蒙类', '家庭启蒙缺失', 24),
(@stage_infant, '语言发育启蒙类', '口齿发育问题', 25),
(@stage_infant, '大运动与精细动作类', '大运动发育滞后', 26),
(@stage_infant, '大运动与精细动作类', '肢体协调性差', 27),
(@stage_infant, '大运动与精细动作类', '精细动作薄弱', 28),
(@stage_infant, '大运动与精细动作类', '运动兴趣低下', 29),
(@stage_infant, '大运动与精细动作类', '家长过度保护', 30),
(@stage_infant, '社交适应能力类', '认生严重', 31),
(@stage_infant, '社交适应能力类', '不会同伴相处', 32),
(@stage_infant, '社交适应能力类', '互动意愿差', 33),
(@stage_infant, '社交适应能力类', '集体适应困难', 34),
(@stage_infant, '社交适应能力类', '自我意识过强', 35),
(@stage_infant, '亲子陪伴家庭教育类', '陪伴质量低', 36),
(@stage_infant, '亲子陪伴家庭教育类', '教育方式极端', 37),
(@stage_infant, '亲子陪伴家庭教育类', '育儿观念分歧', 38),
(@stage_infant, '亲子陪伴家庭教育类', '过度包办代替', 39),
(@stage_infant, '亲子陪伴家庭教育类', '情绪影响孩子', 40),
(@stage_infant, '健康卫生习惯类', '卫生意识薄弱', 41),
(@stage_infant, '健康卫生习惯类', '体质抵抗力差', 42),
(@stage_infant, '健康卫生习惯类', '沉迷电子产品', 43),
(@stage_infant, '健康卫生习惯类', '日常护理不当', 44),
(@stage_infant, '健康卫生习惯类', '卫生习惯未培养', 45),
(@stage_infant, '饮食喂养类', '其它', 999);

-- ========== 3-6岁幼儿园 ==========
SET @stage_kindergarten = (SELECT id FROM life_stages WHERE code = 'kindergarten');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_kindergarten, '饮食喂养问题', '进食抗拒', 1),
(@stage_kindergarten, '饮食喂养问题', '用餐习惯差', 2),
(@stage_kindergarten, '饮食喂养问题', '饮食作息混乱', 3),
(@stage_kindergarten, '饮食喂养问题', '自主进食能力弱', 4),
(@stage_kindergarten, '饮食喂养问题', '家长喂养观念误区', 5),
(@stage_kindergarten, '行为习惯问题', '自律性差', 6),
(@stage_kindergarten, '行为习惯问题', '规则意识淡薄', 7),
(@stage_kindergarten, '行为习惯问题', '自理能力低下', 8),
(@stage_kindergarten, '行为习惯问题', '卫生习惯不良', 9),
(@stage_kindergarten, '性格情绪心理问题', '脾气暴躁易怒', 10),
(@stage_kindergarten, '性格情绪心理问题', '胆小内向自卑', 11),
(@stage_kindergarten, '性格情绪心理问题', '任性自私霸道', 12),
(@stage_kindergarten, '性格情绪心理问题', '专注力缺失', 13),
(@stage_kindergarten, '社交相处问题', '社交胆怯', 14),
(@stage_kindergarten, '社交相处问题', '不懂相处礼仪', 15),
(@stage_kindergarten, '社交相处问题', '同伴矛盾突出', 16),
(@stage_kindergarten, '社交相处问题', '依赖性过重', 17),
(@stage_kindergarten, '语言表达问题', '语言发育迟缓', 18),
(@stage_kindergarten, '语言表达问题', '表达能力不足', 19),
(@stage_kindergarten, '语言表达问题', '不良语言习惯', 20),
(@stage_kindergarten, '家庭教育方式问题', '过度溺爱包办', 21),
(@stage_kindergarten, '家庭教育方式问题', '严厉打骂式教育', 22),
(@stage_kindergarten, '家庭教育方式问题', '家庭教育观念不一致', 23),
(@stage_kindergarten, '家庭教育方式问题', '陪伴缺失', 24),
(@stage_kindergarten, '家庭教育方式问题', '过早超前教育', 25),
(@stage_kindergarten, '电子产品沉迷问题', '沉迷电子产品', 26),
(@stage_kindergarten, '饮食喂养问题', '其它', 999);

-- ========== 7-12岁小学 ==========
SET @stage_primary = (SELECT id FROM life_stages WHERE code = 'primary_school');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_primary, '饮食作息类', '饮食恶习突出', 1),
(@stage_primary, '饮食作息类', '作息严重紊乱', 2),
(@stage_primary, '饮食作息类', '自理饮食观念差', 3),
(@stage_primary, '学习教育类', '学习态度懒散', 4),
(@stage_primary, '学习教育类', '专注力极度薄弱', 5),
(@stage_primary, '学习教育类', '学习习惯极差', 6),
(@stage_primary, '学习教育类', '自律能力缺失', 7),
(@stage_primary, '学习教育类', '抗压能力薄弱', 8),
(@stage_primary, '行为习惯类', '生活自理能力差', 9),
(@stage_primary, '行为习惯类', '时间观念淡薄', 10),
(@stage_primary, '行为习惯类', '规则意识欠缺', 11),
(@stage_primary, '行为习惯类', '劳动意识匮乏', 12),
(@stage_primary, '情绪性格心理类', '叛逆逆反心理强', 13),
(@stage_primary, '情绪性格心理类', '情绪暴躁冲动', 14),
(@stage_primary, '情绪性格心理类', '自卑敏感内向', 15),
(@stage_primary, '情绪性格心理类', '自私自我任性', 16),
(@stage_primary, '人际交往相处类', '社交能力不足', 17),
(@stage_primary, '人际交往相处类', '人际矛盾较多', 18),
(@stage_primary, '人际交往相处类', '不懂礼貌教养', 19),
(@stage_primary, '人际交往相处类', '过度内向胆怯', 20),
(@stage_primary, '家庭亲子教育问题', '亲子沟通严重缺失', 21),
(@stage_primary, '家庭亲子教育问题', '教育方式两极化', 22),
(@stage_primary, '家庭亲子教育问题', '家庭教育意见分歧', 23),
(@stage_primary, '家庭亲子教育问题', '过度攀比施压', 24),
(@stage_primary, '家庭亲子教育问题', '包办过度保护', 25),
(@stage_primary, '电子产品沉迷问题', '沉迷手机游戏短视频', 26),
(@stage_primary, '电子产品沉迷问题', '沉迷网络性格孤僻', 27),
(@stage_primary, '电子产品沉迷问题', '自控力差难管教', 28),
(@stage_primary, '品德思想习惯问题', '缺乏责任心担当', 29),
(@stage_primary, '品德思想习惯问题', '不懂感恩不懂孝顺', 30),
(@stage_primary, '品德思想习惯问题', '存在不良行为', 31),
(@stage_primary, '饮食作息类', '其它', 999);

-- ========== 13-18岁初高中 ==========
SET @stage_middle = (SELECT id FROM life_stages WHERE code = 'middle_high_school');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_middle, '心理情绪类', '情绪极度敏感', 1),
(@stage_middle, '心理情绪类', '内心自卑敏感', 2),
(@stage_middle, '心理情绪类', '情绪抑郁低落', 3),
(@stage_middle, '心理情绪类', '抗压能力差', 4),
(@stage_middle, '心理情绪类', '焦虑烦躁', 5),
(@stage_middle, '心理情绪类', '逆反心理极强', 6),
(@stage_middle, '学习学业类', '学习动力缺失', 7),
(@stage_middle, '学习学业类', '专注力差', 8),
(@stage_middle, '学习学业类', '偏科严重', 9),
(@stage_middle, '学习学业类', '逃避学习', 10),
(@stage_middle, '学习学业类', '没有学习目标', 11),
(@stage_middle, '学习学业类', '考试心态差', 12),
(@stage_middle, '学习学业类', '缺乏自主学习能力', 13),
(@stage_middle, '行为习惯类', '沉迷电子产品', 14),
(@stage_middle, '行为习惯类', '作息混乱', 15),
(@stage_middle, '行为习惯类', '懒惰散漫', 16),
(@stage_middle, '行为习惯类', '消费观念混乱', 17),
(@stage_middle, '行为习惯类', '作息饮食不规律', 18),
(@stage_middle, '行为习惯类', '做事拖拉懒散', 19),
(@stage_middle, '人际交往类', '社交恐惧', 20),
(@stage_middle, '人际交往类', '校园人际关系矛盾', 21),
(@stage_middle, '人际交往类', '过早早恋', 22),
(@stage_middle, '人际交往类', '结交不良玩伴', 23),
(@stage_middle, '人际交往类', '不懂社交分寸', 24),
(@stage_middle, '人际交往类', '讨好型人格', 25),
(@stage_middle, '亲子家庭关系类', '亲子沟通断裂', 26),
(@stage_middle, '亲子家庭关系类', '抵触父母管教', 27),
(@stage_middle, '亲子家庭关系类', '极度叛逆', 28),
(@stage_middle, '亲子家庭关系类', '缺少家庭安全感', 29),
(@stage_middle, '亲子家庭关系类', '家庭矛盾影响孩子', 30),
(@stage_middle, '亲子家庭关系类', '不尊重长辈', 31),
(@stage_middle, '三观品德品格类', '虚荣心强', 32),
(@stage_middle, '三观品德品格类', '责任感缺失', 33),
(@stage_middle, '三观品德品格类', '诚信缺失', 34),
(@stage_middle, '三观品德品格类', '规则意识淡薄', 35),
(@stage_middle, '三观品德品格类', '抗压抗挫能力弱', 36),
(@stage_middle, '三观品德品格类', '自我中心', 37),
(@stage_middle, '身心健康隐藏问题', '早恋情绪反复', 38),
(@stage_middle, '身心健康隐藏问题', '体态心理问题', 39),
(@stage_middle, '身心健康隐藏问题', '叛逆期叛逆冲动', 40),
(@stage_middle, '身心健康隐藏问题', '早恋心理障碍', 41),
(@stage_middle, '心理情绪类', '其它', 999);

-- ========== 19-22+岁大学生 ==========
SET @stage_college = (SELECT id FROM life_stages WHERE code = 'college');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_college, '独立生存能力类', '生活自理能力差', 1),
(@stage_college, '独立生存能力类', '缺乏规划能力', 2),
(@stage_college, '独立生存能力类', '时间观念薄弱', 3),
(@stage_college, '独立生存能力类', '身体素质差', 4),
(@stage_college, '独立生存能力类', '动手能力弱', 5),
(@stage_college, '金钱消费与财商类', '消费无节制', 6),
(@stage_college, '金钱消费与财商类', '盲目攀比消费', 7),
(@stage_college, '金钱消费与财商类', '不懂赚钱辛苦', 8),
(@stage_college, '金钱消费与财商类', '缺乏风险意识', 9),
(@stage_college, '金钱消费与财商类', '不懂理财规划', 10),
(@stage_college, '学业职业发展类', '大学迷茫躺平', 11),
(@stage_college, '学业职业发展类', '自律性缺失', 12),
(@stage_college, '学业职业发展类', '没有升学规划', 13),
(@stage_college, '学业职业发展类', '抗压能力差', 14),
(@stage_college, '学业职业发展类', '眼高手低', 15),
(@stage_college, '学业职业发展类', '缺乏职业定力', 16),
(@stage_college, '学业职业发展类', '没有职业规划', 17),
(@stage_college, '学业职业发展类', '抗压承受力弱', 18),
(@stage_college, '学业职业发展类', '缺少上进心', 19),
(@stage_college, '人际交往与情商类', '社交能力薄弱', 20),
(@stage_college, '人际交往与情商类', '情商偏低', 21),
(@stage_college, '人际交往与情商类', '职场不懂相处', 22),
(@stage_college, '人际交往与情商类', '不懂拒绝', 23),
(@stage_college, '人际交往与情商类', '社交恐惧', 24),
(@stage_college, '人际交往与情商类', '内心缺乏安全感', 25),
(@stage_college, '情绪心态心理类', '心态脆弱敏感', 26),
(@stage_college, '情绪心态心理类', '情绪消极悲观', 27),
(@stage_college, '情绪心态心理类', '心态浮躁急躁', 28),
(@stage_college, '情绪心态心理类', '自卑不自信', 29),
(@stage_college, '情绪心态心理类', '情绪自控力差', 30),
(@stage_college, '情绪心态心理类', '内心缺乏安全感', 31),
(@stage_college, '婚恋情感家庭观类', '恋爱观不成熟', 32),
(@stage_college, '婚恋情感家庭观类', '情感容易受伤', 33),
(@stage_college, '婚恋情感家庭观类', '恐婚恐恋', 34),
(@stage_college, '婚恋情感家庭观类', '择偶眼光偏激', 35),
(@stage_college, '婚恋情感家庭观类', '不懂包容体谅', 36),
(@stage_college, '婚恋情感家庭观类', '缺少家庭责任感', 37),
(@stage_college, '思想三观责任类', '责任心淡薄', 38),
(@stage_college, '思想三观责任类', '缺乏感恩之心', 39),
(@stage_college, '思想三观责任类', '没有规则底线', 40),
(@stage_college, '思想三观责任类', '抗压抗挫能力极差', 41),
(@stage_college, '思想三观责任类', '三观浅薄', 42),
(@stage_college, '思想三观责任类', '贪图安逸享乐', 43),
(@stage_college, '亲子相处隔阂类', '亲子沟通疏远', 44),
(@stage_college, '亲子相处隔阂类', '反感父母说教管束', 45),
(@stage_college, '亲子相处隔阂类', '报喜不报忧', 46),
(@stage_college, '亲子相处隔阂类', '亲情淡薄', 47),
(@stage_college, '亲子相处隔阂类', '思想观念代沟严重', 48),
(@stage_college, '自律底线品行类', '自控力极差', 49),
(@stage_college, '自律底线品行类', '做事缺乏诚信', 50),
(@stage_college, '自律底线品行类', '意志力薄弱', 51),
(@stage_college, '自律底线品行类', '遇事逃避推卸', 52),
(@stage_college, '独立生存能力类', '其它', 999);

-- ========== 步入社会 ==========
SET @stage_society = (SELECT id FROM life_stages WHERE code = 'society');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_society, '独立生存能力类', '生活自理能力差', 1),
(@stage_society, '独立生存能力类', '缺乏规划能力', 2),
(@stage_society, '独立生存能力类', '时间观念薄弱', 3),
(@stage_society, '独立生存能力类', '身体素质差', 4),
(@stage_society, '独立生存能力类', '动手能力弱', 5),
(@stage_society, '金钱消费与财商类', '消费无节制', 6),
(@stage_society, '金钱消费与财商类', '盲目攀比消费', 7),
(@stage_society, '金钱消费与财商类', '不懂赚钱辛苦', 8),
(@stage_society, '金钱消费与财商类', '缺乏风险意识', 9),
(@stage_society, '金钱消费与财商类', '不懂理财规划', 10),
(@stage_society, '学业职业发展类', '眼高手低', 11),
(@stage_society, '学业职业发展类', '缺乏职业定力', 12),
(@stage_society, '学业职业发展类', '没有职业规划', 13),
(@stage_society, '学业职业发展类', '抗压承受力弱', 14),
(@stage_society, '学业职业发展类', '缺少上进心', 15),
(@stage_society, '人际交往与情商类', '社交能力薄弱', 16),
(@stage_society, '人际交往与情商类', '情商偏低', 17),
(@stage_society, '人际交往与情商类', '职场不懂相处', 18),
(@stage_society, '人际交往与情商类', '不懂拒绝', 19),
(@stage_society, '人际交往与情商类', '社交恐惧', 20),
(@stage_society, '人际交往与情商类', '内心缺乏安全感', 21),
(@stage_society, '情绪心态心理类', '心态脆弱敏感', 22),
(@stage_society, '情绪心态心理类', '情绪消极悲观', 23),
(@stage_society, '情绪心态心理类', '心态浮躁急躁', 24),
(@stage_society, '情绪心态心理类', '自卑不自信', 25),
(@stage_society, '情绪心态心理类', '情绪自控力差', 26),
(@stage_society, '婚恋情感家庭观类', '恋爱观不成熟', 27),
(@stage_society, '婚恋情感家庭观类', '情感容易受伤', 28),
(@stage_society, '婚恋情感家庭观类', '恐婚恐恋', 29),
(@stage_society, '婚恋情感家庭观类', '择偶眼光偏激', 30),
(@stage_society, '婚恋情感家庭观类', '不懂包容体谅', 31),
(@stage_society, '婚恋情感家庭观类', '缺少家庭责任感', 32),
(@stage_society, '思想三观责任类', '责任心淡薄', 33),
(@stage_society, '思想三观责任类', '缺乏感恩之心', 34),
(@stage_society, '思想三观责任类', '没有规则底线', 35),
(@stage_society, '思想三观责任类', '抗压抗挫能力极差', 36),
(@stage_society, '亲子相处隔阂类', '亲子沟通疏远', 37),
(@stage_society, '亲子相处隔阂类', '反感父母说教管束', 38),
(@stage_society, '亲子相处隔阂类', '报喜不报忧', 39),
(@stage_society, '亲子相处隔阂类', '亲情淡薄', 40),
(@stage_society, '亲子相处隔阂类', '思想观念代沟严重', 41),
(@stage_society, '自律底线品行类', '自控力极差', 42),
(@stage_society, '自律底线品行类', '做事缺乏诚信', 43),
(@stage_society, '自律底线品行类', '意志力薄弱', 44),
(@stage_society, '自律底线品行类', '遇事逃避推卸', 45),
(@stage_society, '独立生存能力类', '其它', 999);

-- ========== 婚前婚后 ==========
SET @stage_marriage = (SELECT id FROM life_stages WHERE code = 'marriage');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_marriage, '婚前阶段-原生家庭观念植入问题', '父母过度包办择偶', 1),
(@stage_marriage, '婚前阶段-原生家庭观念植入问题', '家庭门第观念重', 2),
(@stage_marriage, '婚前阶段-原生家庭观念植入问题', '父母婚姻不幸', 3),
(@stage_marriage, '婚前阶段-性格教养遗留问题', '从小溺爱娇惯', 4),
(@stage_marriage, '婚前阶段-性格教养遗留问题', '从小严厉打压', 5),
(@stage_marriage, '婚前阶段-性格教养遗留问题', '单亲/留守家庭长大', 6),
(@stage_marriage, '婚前阶段-婚恋认知教育缺失', '家庭从不进行情感教育', 7),
(@stage_marriage, '婚前阶段-婚恋认知教育缺失', '缺少金钱观教育，消费两极分', 8),
(@stage_marriage, '婚前阶段-婚恋认知教育缺失', '无家庭责任引导', 9),
(@stage_marriage, '婚前阶段-双方家庭相处隐患', '双方父母生活习惯', 10),
(@stage_marriage, '婚前阶段-双方家庭相处隐患', '彩礼、婚房、财产划分观念分', 11),
(@stage_marriage, '婚前阶段-双方家庭相处隐患', '婆媳、翁婿提前对立', 12),
(@stage_marriage, '婚后阶段-夫妻二人相处类问题', '沟通能力缺失', 13),
(@stage_marriage, '婚后阶段-夫妻二人相处类问题', '情绪管理失控', 14),
(@stage_marriage, '婚后阶段-夫妻二人相处类问题', '家庭分工失衡', 15),
(@stage_marriage, '婚后阶段-夫妻二人相处类问题', '边界感模糊', 16),
(@stage_marriage, '婚后阶段-两代长辈家庭矛盾', '长辈过度干涉小家庭生活', 17),
(@stage_marriage, '婚后阶段-两代长辈家庭矛盾', '赡养观念分歧', 18),
(@stage_marriage, '婚后阶段-两代长辈家庭矛盾', '生活习俗冲突', 19),
(@stage_marriage, '婚后阶段-金钱与物质挂念矛盾', '消费观念不合', 20),
(@stage_marriage, '婚后阶段-金钱与物质挂念矛盾', '财产观念对立', 21),
(@stage_marriage, '婚后阶段-金钱与物质挂念矛盾', '人情开销分歧', 22),
(@stage_marriage, '婚后阶段-子女教育核心家庭问题', '夫妻教育理念冲突', 23),
(@stage_marriage, '婚后阶段-子女教育核心家庭问题', '隔代教育矛盾', 24),
(@stage_marriage, '婚后阶段-子女教育核心家庭问题', '家庭教育缺位', 25),
(@stage_marriage, '婚后阶段-子女教育核心家庭问题', '家庭氛围影响孩子', 26),
(@stage_marriage, '婚后阶段-家庭责任与三观问题', '家庭责任感淡薄', 27),
(@stage_marriage, '婚后阶段-家庭责任与三观问题', '三观长期不合', 28),
(@stage_marriage, '婚后阶段-家庭责任与三观问题', '家庭忠诚意识薄弱', 29),
(@stage_marriage, '婚后阶段-生活习惯衍生矛盾', '作息、卫生、饮食习惯差异', 30),
(@stage_marriage, '婚后阶段-生活习惯衍生矛盾', '社交观念不同', 31),
(@stage_marriage, '婚前阶段-原生家庭观念植入问题', '其它', 999);

-- ========== 分家|财产分割 ==========
SET @stage_property = (SELECT id FROM life_stages WHERE code = 'property_division');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_property, '思想观念层面', '公平认知教育缺失', 1),
(@stage_property, '思想观念层面', '亲情淡薄，功利化教养', 2),
(@stage_property, '思想观念层面', '传统家产观念固化', 3),
(@stage_property, '思想观念层面', '责任与利益认知失衡', 4),
(@stage_property, '家庭教养性格引发问题', '自私利己型性格', 5),
(@stage_property, '家庭教养性格引发问题', '懦弱被动不懂争取', 6),
(@stage_property, '家庭教养性格引发问题', '偏激冲动遇事极端', 7),
(@stage_property, '家庭教养性格引发问题', '依赖性强缺乏独立', 8),
(@stage_property, '父母家庭教育出事问题', '父母偏心处事不公', 9),
(@stage_property, '父母家庭教育出事问题', '事前无规划，处事含糊', 10),
(@stage_property, '父母家庭教育出事问题', '偏袒溺爱，过度帮扶', 11),
(@stage_property, '父母家庭教育出事问题', '逃避做主，推卸责任', 12),
(@stage_property, '父母家庭教育出事问题', '财产界限模糊不清', 13),
(@stage_property, '子女兄弟姐妹相处问题', '付出不对等，心生怨气', 14),
(@stage_property, '子女兄弟姐妹相处问题', '互相猜忌不信任', 15),
(@stage_property, '子女兄弟姐妹相处问题', '攀比攀比心理严重', 16),
(@stage_property, '子女兄弟姐妹相处问题', '成家后小家利益优先', 17),
(@stage_property, '分割流程与规划类问题', '口头约定，没有书面凭证', 18),
(@stage_property, '分割流程与规划类问题', '不动产分配争议最大', 19),
(@stage_property, '分割流程与规划类问题', '债务与资产分割脱节', 20),
(@stage_property, '分割流程与规划类问题', '忽略老人养老后续安排', 21),
(@stage_property, '家风家庭气氛根源总结', '和睦公正的家风', 22),
(@stage_property, '家风家庭气氛根源总结', '家风自私、偏心、计较、重利轻情', 23),
(@stage_property, '家风家庭气氛根源总结', '所有分家财产纠纷', 24),
(@stage_property, '思想观念层面', '其它', 999);

-- ========== 养老|赡养 ==========
SET @stage_elderly = (SELECT id FROM life_stages WHERE code = 'elderly_care');

INSERT INTO consultation_issues (stage_id, category_name, issue_name, sort_order) VALUES
(@stage_elderly, '思想认知教育缺失', '孝道观念教育淡薄', 1),
(@stage_elderly, '思想认知教育缺失', '权利义务认知错位', 2),
(@stage_elderly, '思想认知教育缺失', '利己价值观根深蒂固', 3),
(@stage_elderly, '思想认知教育缺失', '养老责任认知模糊', 4),
(@stage_elderly, '父母早年家庭教育方式遗留问题', '从小过度溺爱纵容', 5),
(@stage_elderly, '父母早年家庭教育方式遗留问题', '家庭教育偏心失衡', 6),
(@stage_elderly, '父母早年家庭教育方式遗留问题', '父母自身榜样缺失', 7),
(@stage_elderly, '父母早年家庭教育方式遗留问题', '缺少责任担当培养', 8),
(@stage_elderly, '多子女家庭赡养纠纷', '赡养分工不均引发矛盾', 9),
(@stage_elderly, '多子女家庭赡养纠纷', '互相攀比互相推诿', 10),
(@stage_elderly, '多子女家庭赡养纠纷', '财产分配与赡养不挂钩', 11),
(@stage_elderly, '多子女家庭赡养纠纷', '子女家庭意见不统一', 12),
(@stage_elderly, '经济物质层面赡养问题', '赡养费用分摊争执', 13),
(@stage_elderly, '经济物质层面赡养问题', '嫌弃老人拖累家境', 14),
(@stage_elderly, '经济物质层面赡养问题', '老人财产钱财分配矛盾', 15),
(@stage_elderly, '生活照料与精神赡养问题', '只给钱不陪伴', 16),
(@stage_elderly, '生活照料与精神赡养问题', '嫌弃老人生活习惯', 17),
(@stage_elderly, '生活照料与精神赡养问题', '忽视心理情感需求', 18),
(@stage_elderly, '生活照料与精神赡养问题', '生病护理互相推脱', 19),
(@stage_elderly, '家庭观念与风俗引发矛盾', '重男轻女养老偏见', 20),
(@stage_elderly, '家庭观念与风俗引发矛盾', '居住赡养方式分歧', 21),
(@stage_elderly, '家庭观念与风俗引发矛盾', '婆媳翁婿相处矛盾', 22),
(@stage_elderly, '单亲、特殊家庭养老问题', '早年亲子关系疏远', 23),
(@stage_elderly, '单亲、特殊家庭养老问题', '重组家庭赡养复杂', 24),
(@stage_elderly, '思想认知教育缺失', '其它', 999);
